<?xml version="1.0" encoding="UTF-8"?>
<!--

   Copyright (C) 2002-2024 Jahia Solutions Group SA. All rights reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>jahia-modules</artifactId>
        <groupId>org.jahia.modules</groupId>
        <version>8.2.2.0</version>
    </parent>
    <artifactId>formidable</artifactId>
    <name>Formidable</name>
    <version>0.5.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>Multi-module project containing the Formidable front-end module and its Cypress test suite.</description>
    <licenses>
        <license>
            <name>GNU General Public License</name>
            <url>http://www.gnu.org/licenses/gpl.txt</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>JAHIA Sustainable Enterprise License</name>
            <url>https://github.com/Jahia/maven-archetypes/blob/master/license/jsel.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:git@github.com:Jahia/formidable.git</connection>
        <developerConnection>scm:git:git@github.com:Jahia/formidable.git</developerConnection>
        <url>scm:git:git@github.com:Jahia/formidable.git</url>
        <tag>HEAD</tag>
    </scm>

    <modules>
        <module>formidable-engine</module>
        <module>formidable-elements</module>
        <module>formidable-extended-inputs</module>
        <module>formidable-salesforce</module>
        <module>formidable-hubspot</module>
        <module>formidable-efficy</module>
        <module>jahia-test-module</module>
    </modules>

    <properties>
        <tika.version>3.3.2</tika.version>
        <jahia.server.version>8.2.2.0</jahia.server.version>
        <javax.jcr.version>2.0</javax.jcr.version>
        <javax.servlet.api.version>3.1.0</javax.servlet.api.version>
        <slf4j.version>1.7.36</slf4j.version>
        <osgi.version>7.0.0</osgi.version>
        <osgi.annotation.version>7.0.0</osgi.annotation.version>
        <json.version>20231013</json.version>
        <javax.mail.version>1.6.2</javax.mail.version>
        <activation.version>1.1.1</activation.version>
        <spring.context.support.version>3.2.18.RELEASE_OSGI</spring.context.support.version>
        <commons.lang.version>2.6</commons.lang.version>
        <commons.fileupload.version>1.6.0</commons.fileupload.version>
        <commons.io.version>2.16.1</commons.io.version>
        <commons.text.version>1.10.0</commons.text.version>
        <junit.jupiter.version>5.10.2</junit.jupiter.version>
        <mockito.version>5.12.0</mockito.version>
        <exec-maven-plugin.version>3.6.3</exec-maven-plugin.version>
        <maven-antrun-plugin.version>3.1.0</maven-antrun-plugin.version>
        <maven-clean-plugin.version>3.4.0</maven-clean-plugin.version>
        <maven-dependency-plugin.version>3.6.0</maven-dependency-plugin.version>
        <build-helper-maven-plugin.version>3.6.0</build-helper-maven-plugin.version>
        <buildnumber-maven-plugin.version>3.2.1</buildnumber-maven-plugin.version>
        <jahia.plugin.version>6.9</jahia.plugin.version>
    </properties>

    <repositories>
        <repository>
            <id>jahia-public</id>
            <name>Jahia Public Repository</name>
            <url>https://devtools.jahia.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jahia.server</groupId>
                <artifactId>jahia-impl</artifactId>
                <version>${jahia.server.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.jcr</groupId>
                <artifactId>jcr</artifactId>
                <version>${javax.jcr.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <version>${javax.servlet.api.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>osgi.cmpn</artifactId>
                <version>${osgi.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>osgi.annotation</artifactId>
                <version>${osgi.annotation.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.json</groupId>
                <artifactId>json</artifactId>
                <version>${json.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.sun.mail</groupId>
                <artifactId>javax.mail</artifactId>
                <version>${javax.mail.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.activation</groupId>
                <artifactId>activation</artifactId>
                <version>${activation.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context-support</artifactId>
                <version>${spring.context.support.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>${tika.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-lang</groupId>
                <artifactId>commons-lang</artifactId>
                <version>${commons.lang.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>commons-fileupload</groupId>
                <artifactId>commons-fileupload</artifactId>
                <version>${commons.fileupload.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons.io.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons.text.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${exec-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>${maven-antrun-plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>${build-helper-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>buildnumber-maven-plugin</artifactId>
                    <version>${buildnumber-maven-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <!-- The release-prepare profile syncs every package.json with the maven version
                         (and yarn.lock checksums may change) during the regular build; the
                         commit-synced-files execution then commits what changed, module by module,
                         before the release plugin commits the poms. -->
                    <preparationGoals>-P release-prepare clean verify exec:exec@commit-synced-files</preparationGoals>
                    <completionGoals>-P release-prepare clean install exec:exec@commit-synced-files</completionGoals>
                    <releaseProfiles>release-perform</releaseProfiles>
                    <useReleaseProfile>true</useReleaseProfile>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <!-- create a ${timestamp} Maven variable with the build timestamp -->
                        <goals>
                            <goal>create-timestamp</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- use UTC to ensure timestamps between builds are in correct SemVer order -->
                    <timestampFormat>yyyyMMddHHmmssSSS</timestampFormat>
                    <timezone>UTC</timezone>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>2.7.9</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>makeAggregateBom</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <projectType>library</projectType>
                    <schemaVersion>1.4</schemaVersion>
                    <includeBomSerialNumber>true</includeBomSerialNumber>
                    <includeCompileScope>true</includeCompileScope>
                    <includeProvidedScope>false</includeProvidedScope>
                    <includeRuntimeScope>true</includeRuntimeScope>
                    <includeSystemScope>false</includeSystemScope>
                    <includeTestScope>false</includeTestScope>
                    <includeLicenseText>false</includeLicenseText>
                    <outputReactorProjects>true</outputReactorProjects>
                    <outputFormat>json</outputFormat>
                    <outputName>java-bom.cdx</outputName>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release-prepare</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <!-- Keep every module's package.json in sync with the maven version.
                                 Inherited by the modules whose parent is this pom (the test
                                 modules have their own parent and their own wiring); each
                                 carries a copy of .m2/sync-version.js resolving package.json
                                 from the working directory. -->
                            <execution>
                                <id>sync-version</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>node</executable>
                                    <arguments>
                                        <argument>${basedir}/.m2/sync-version.js</argument>
                                        <argument>${project.version}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <!-- Commits the files sync-version rewrote, module by module and only when
                                 they changed. Not bound to a phase: the release plugin invokes it as
                                 exec:exec@commit-synced-files after the build (preparation and
                                 completion goals). scm:checkin cannot do this — it fails on a module
                                 that has nothing to commit (#155). -->
                            <execution>
                                <id>commit-synced-files</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>bash</executable>
                                    <arguments>
                                        <argument>${maven.multiModuleProjectDirectory}/.m2/commit-synced-files.sh</argument>
                                        <argument>${project.version}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>dev</id>
            <properties>
                <yarn.arguments>build</yarn.arguments>
                <cyclonedx.skip>true</cyclonedx.skip>
            </properties>
        </profile>
    </profiles>

</project>
